#!/bin/zsh

# ****************************************************************************************************
# NAME: 	bearerToken.zsh
# DATE: 	7th October 2025
# ****************************************************************************************************

# ****************************************************************************************************

# ********** DISCLAIMER **********
# --------------------------------
# This script has been sourced from Apple's documentation. 
# For more details about this specific script visit: https://developer.apple.com/documentation/apple-school-and-business-manager-api/implementing-oauth-for-the-apple-school-and-business-manager-api
# ****************************************************************************************************

# ****************************************************************************************************
# Usage
# --------------------
# This script uses the client assertion generated by the apiAssertionGenerator.py script. Please run that script and plug in the assertion in the client_assertion varaible.
# You will also need to copy the client id from the API account. This is the same as the client_id used in the apiAssertionGenerator.py script.

# To run the script:
# /bin/zsh /path/to/bearerToken.zsh

# Copy the output from stdout. This will be used as the access token while making the API calls.

# This script works with both Apple Business Manager as well as Apple School Manager. Replace all occurances of 'school' with 'business' or the other way round depending on which service you are accessing.
# ****************************************************************************************************

# ****************************************************************************************************
# **WARNING**: Please test the script before using it.
# ****************************************************************************************************

# ****************************************************************************************************
# ********** SCRIPT STARTS HERE **********
# ****************************************************************************************************

# Variables
client_id="SCHOOLAPI.----------"
client_assertion="----------"

/usr/bin/curl -s -X POST \
-H 'Host: account.apple.com' \
-H 'Content-Type: application/x-www-form-urlencoded' \
"https://account.apple.com/auth/oauth2/token?grant_type=client_credentials&client_id=${client_id}&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=${client_assertion}&scope=school.api" > /Users/Shared/response.json

# Extract the access token from the entire response
/usr/bin/plutil -extract access_token raw /Users/Shared/response.json

# ****************************************************************************************************
# ********** SCRIPT ENDS HERE **********
# ****************************************************************************************************